---
version: "3.5"
services:
  motioneye:
    image: femtodata/motioneye:dev-amd64
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - "./etc_motioneye:/etc/motioneye"
      - "./var_lib_motioneye:/var/lib/motioneye"

# volumes:
#   etc_motioneye:
#   var_lib_motioneye:
